import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { REPO_ROOT, TSX_BIN } from "../../runner/src/paths.ts";
import { sync } from "../lib/sync.ts";
import { makeStudyRepo, put } from "./fixture.ts";

const read = (root: string, rel: string) => readFileSync(path.join(root, rel), "utf8");

describe("sync", () => {
  it("writes the problem index grouped by pattern", () => {
    const root = makeStudyRepo();
    sync(root);
    expect(read(root, "INDEX.md")).toBe(
      [
        "# Problems",
        "",
        "<!-- Generated by `pnpm sync`. Do not edit by hand. -->",
        "",
        "Status: ✓ solved · … solving · ↺ revealed · ○ todo",
        "",
        "## arrays-hashing (1/1)",
        "",
        "- ✓ [lc-0001 · Two Sum](problems/lc-0001-two-sum/README.md) · easy",
        "",
        "## stack (0/1)",
        "",
        "- … [lc-0020 · Valid Parentheses](problems/lc-0020-valid-parentheses/README.md) · easy",
        "",
      ].join("\n"),
    );
  });

  it("writes the concept index with a learning path and missing concepts", () => {
    const root = makeStudyRepo();
    sync(root);
    expect(read(root, "concepts/INDEX.md")).toBe(
      [
        "# Concepts",
        "",
        "<!-- Generated by `pnpm sync`. Do not edit by hand. -->",
        "",
        "## Learning path",
        "",
        "1. [Arrays](arrays/README.md) · mastered",
        "2. [Hash map](hash-map/README.md) · learning — requires: arrays",
        "",
        "## By status",
        "",
        "### mastered (1)",
        "",
        "- [Arrays](arrays/README.md)",
        "",
        "### learning (1)",
        "",
        "- [Hash map](hash-map/README.md)",
        "",
        "### new (0)",
        "",
        "## Missing",
        "",
        "- stack — referenced by lc-0020",
        "",
      ].join("\n"),
    );
  });

  it("fills the auto sections of problems and concepts", () => {
    const root = makeStudyRepo();
    sync(root);
    expect(read(root, "problems/lc-0001-two-sum/README.md")).toContain(
      "<!-- auto:concepts -->\n- [Hash map](../../concepts/hash-map/README.md) · learning\n<!-- /auto -->",
    );
    expect(read(root, "problems/lc-0020-valid-parentheses/README.md")).toContain(
      "<!-- auto:concepts -->\n- stack (missing)\n<!-- /auto -->",
    );
    const hashMap = read(root, "concepts/hash-map/README.md");
    expect(hashMap).toContain("<!-- auto:exercises -->\n- ✓ [01 · First repeat](exercises/01-first-repeat/README.md)\n<!-- /auto -->");
    expect(hashMap).toContain("<!-- auto:problems -->\n- ✓ [lc-0001 · Two Sum](../../problems/lc-0001-two-sum/README.md)\n<!-- /auto -->");
    const arrays = read(root, "concepts/arrays/README.md");
    expect(arrays).toContain("<!-- auto:exercises -->\n_No exercises yet._\n<!-- /auto -->");
    expect(arrays).toContain("<!-- auto:problems -->\n_No problems yet._\n<!-- /auto -->");
    expect(hashMap.startsWith("---\nslug: hash-map\n")).toBe(true);
  });

  it("is idempotent and reports what changed", () => {
    const root = makeStudyRepo();
    expect(sync(root)).toEqual([
      "problems/lc-0001-two-sum/README.md",
      "problems/lc-0020-valid-parentheses/README.md",
      "concepts/arrays/README.md",
      "concepts/hash-map/README.md",
      "INDEX.md",
      "concepts/INDEX.md",
    ]);
    expect(sync(root)).toEqual([]);
  });

  it("leaves files without markers untouched", () => {
    const root = makeStudyRepo();
    const custom = "---\nid: lc-0001\ntitle: Two Sum\n---\n# no markers here\n";
    put(root, "problems/lc-0001-two-sum/README.md", custom);
    sync(root);
    expect(read(root, "problems/lc-0001-two-sum/README.md")).toBe(custom);
  });

  it("runs from the CLI", () => {
    const root = makeStudyRepo();
    const run = (...args: string[]) =>
      spawnSync(TSX_BIN, ["scripts/sync.ts", ...args], { cwd: REPO_ROOT, env: { ...process.env, ALGO_ROOT: root }, encoding: "utf8" });
    expect(run().stdout).toContain("Updated:\n  problems/lc-0001-two-sum/README.md");
    expect(run().stdout).toContain("Everything is in sync.");
  });
});
