import {
  type ConceptEntry,
  type ExerciseEntry,
  type ProblemEntry,
  type RepoModel,
  str,
  strList,
} from "../../lib/repo.ts";

export const STATUS_MARK: Record<string, string> = { solved: "✓", solving: "…", revealed: "↺", todo: "○" };
export const GENERATED_NOTE = "<!-- Generated by `pnpm sync`. Do not edit by hand. -->";

const mark = (status: unknown): string => STATUS_MARK[str(status)] ?? "?";
const titleOf = (entry: ProblemEntry | ExerciseEntry | ConceptEntry): string => str(entry.data.title, entry.folder);

export function conceptBySlug(repo: RepoModel): Map<string, ConceptEntry> {
  return new Map(repo.concepts.map((concept) => [concept.slug, concept]));
}

/** Topological order of `requires` (alphabetical within a level). Cycle members go last. */
export function learningPath(concepts: ConceptEntry[]): string[] {
  const slugs = concepts.map((concept) => concept.slug);
  const known = new Set(slugs);
  const requires = new Map(concepts.map((c) => [c.slug, strList(c.data.requires).filter((r) => known.has(r))]));
  const done = new Set<string>();
  const order: string[] = [];
  while (order.length < slugs.length) {
    const ready = slugs.filter((s) => !done.has(s) && requires.get(s)!.every((r) => done.has(r))).sort();
    if (ready.length === 0) {
      order.push(...slugs.filter((s) => !done.has(s)).sort());
      break;
    }
    for (const slug of ready) {
      done.add(slug);
      order.push(slug);
    }
  }
  return order;
}

/** Concept slugs referenced by problems (concepts) or concepts (requires/related) that do not exist. */
export function missingConcepts(repo: RepoModel): Map<string, string[]> {
  const known = new Set(repo.concepts.map((concept) => concept.slug));
  const missing = new Map<string, string[]>();
  const note = (slug: string, by: string): void => {
    if (known.has(slug)) return;
    const list = missing.get(slug) ?? [];
    if (!list.includes(by)) list.push(by);
    missing.set(slug, list);
  };
  for (const problem of repo.problems) for (const slug of strList(problem.data.concepts)) note(slug, problem.folderId);
  for (const concept of repo.concepts) {
    for (const slug of [...strList(concept.data.requires), ...strList(concept.data.related)]) note(slug, concept.slug);
  }
  return missing;
}

export function renderProblemIndex(repo: RepoModel): string {
  const groups = new Map<string, ProblemEntry[]>();
  for (const problem of repo.problems) {
    const patterns = strList(problem.data.patterns);
    for (const pattern of patterns.length > 0 ? patterns : ["(no pattern yet)"]) {
      groups.set(pattern, [...(groups.get(pattern) ?? []), problem]);
    }
  }
  const lines = ["# Problems", "", GENERATED_NOTE, "", "Status: ✓ solved · … solving · ↺ revealed · ○ todo", ""];
  if (groups.size === 0) lines.push("_No problems yet. Paste one into Claude Code to start._", "");
  for (const pattern of [...groups.keys()].sort()) {
    const items = groups.get(pattern)!;
    const solved = items.filter((p) => p.data.status === "solved").length;
    lines.push(`## ${pattern} (${solved}/${items.length})`, "");
    for (const p of items) {
      lines.push(`- ${mark(p.data.status)} [${p.folderId} · ${titleOf(p)}](problems/${p.folder}/README.md) · ${str(p.data.difficulty, "?")}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function renderConceptIndex(repo: RepoModel): string {
  const bySlug = conceptBySlug(repo);
  const lines = ["# Concepts", "", GENERATED_NOTE, "", "## Learning path", ""];
  const order = learningPath(repo.concepts);
  if (order.length === 0) lines.push("_No concepts yet._");
  order.forEach((slug, i) => {
    const concept = bySlug.get(slug)!;
    const requires = strList(concept.data.requires);
    lines.push(
      `${i + 1}. [${titleOf(concept)}](${slug}/README.md) · ${str(concept.data.status, "?")}${requires.length ? ` — requires: ${requires.join(", ")}` : ""}`,
    );
  });
  lines.push("", "## By status", "");
  for (const status of ["mastered", "learning", "new"]) {
    const items = repo.concepts.filter((concept) => concept.data.status === status);
    lines.push(`### ${status} (${items.length})`, "");
    for (const concept of items) lines.push(`- [${titleOf(concept)}](${concept.slug}/README.md)`);
    if (items.length > 0) lines.push("");
  }
  const missing = missingConcepts(repo);
  lines.push("## Missing", "");
  if (missing.size === 0) lines.push("_None._");
  for (const slug of [...missing.keys()].sort()) lines.push(`- ${slug} — referenced by ${missing.get(slug)!.join(", ")}`);
  lines.push("");
  return lines.join("\n");
}

export function renderProblemConcepts(problem: ProblemEntry, bySlug: Map<string, ConceptEntry>): string {
  const slugs = strList(problem.data.concepts);
  if (slugs.length === 0) return "_No concepts linked yet._";
  return slugs
    .map((slug) => {
      const concept = bySlug.get(slug);
      return concept
        ? `- [${titleOf(concept)}](../../concepts/${slug}/README.md) · ${str(concept.data.status, "?")}`
        : `- ${slug} (missing)`;
    })
    .join("\n");
}

export function renderConceptExercises(concept: ConceptEntry, repo: RepoModel): string {
  const items = repo.exercises.filter((exercise) => exercise.concept === concept.slug);
  if (items.length === 0) return "_No exercises yet._";
  return items
    .map((e) => `- ${mark(e.data.status)} [${e.folderId.split("/")[1]} · ${titleOf(e)}](exercises/${e.folder}/README.md)`)
    .join("\n");
}

export function renderConceptProblems(concept: ConceptEntry, repo: RepoModel): string {
  const items = repo.problems.filter((problem) => strList(problem.data.concepts).includes(concept.slug));
  if (items.length === 0) return "_No problems yet._";
  return items
    .map((p) => `- ${mark(p.data.status)} [${p.folderId} · ${titleOf(p)}](../../problems/${p.folder}/README.md)`)
    .join("\n");
}
